name: Deploy Turborepo Remote Cache to Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Build
        run: pnpm build

      - name: Clean node_modules
        run: rm -rf node_modules

      - name: Install Production Dependencies
        run: pnpm install --prod --node-linker=hoisted --ignore-scripts

      - name: Zip node_modules
        shell: bash
        run: zip -r release.zip node_modules -q

      - name: Zip dist
        shell: bash
        run: zip -r release.zip dist

      - name: Zip az host file
        shell: bash
        run: zip -r release.zip host.json

      - name: Zip az package.json
        shell: bash
        run: zip -r release.zip package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: Unzip artifact for deployment
        shell: bash
        run: |
          mkdir -p ./out/app
          unzip release.zip -d ./out/app

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        with:
          app-name: ps-turborepo-remote-cache-az-function
          package: ./out/app
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
